# Generated by Django 6.0.6 on 2026-06-13 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atletas', '0002_remove_atleta_categoria_remove_atleta_coach_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('estrategia', models.CharField(max_length=150, unique=True)),
                ('unidad_de_medida', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_crudos', models.JSONField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('clima_temperatura', models.FloatField(blank=True, null=True)),
                ('clima_humedad', models.IntegerField(blank=True, null=True)),
                ('clima_condicion', models.CharField(blank=True, max_length=100, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('tipo_prueba', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pruebas.tipoprueba')),
            ],
        ),
    ]
