# Generated by Django 6.0.6 on 2026-06-13 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='coach',
        ),
        migrations.CreateModel(
            name='HistorialAtletaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_temporada', models.IntegerField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddConstraint(
            model_name='historialatletacategoria',
            constraint=models.UniqueConstraint(fields=('atleta', 'categoria', 'anio_temporada'), name='unique_historial_temporada'),
        ),
    ]
